const AF=Object.getPrototypeOf(async function(){}).constructor;const H=await (new AF('figma',(await figma.getNodeByIdAsync('4:2')).characters))(figma);const {P,T,A,ad,spacer,I,pill,brandPill,btn,card,bar,hr,dot,kv,screen,section,dsb,dhead}=H;
const pg=await figma.getNodeByIdAsync('1:5');await figma.setCurrentPageAsync(pg);
const S=section(pg,'Scenario 2 · Short on the dock',0,3500,2640,1400);
const sc=A('V',{n:'Scenario brief',bg:'bg/ink',r:20,p:36,gap:18,w:620});S.appendChild(sc);sc.x=80;sc.y=200;
ad(sc,pill('DEGRADATION SCENARIO 2','warning',{solid:true,lg:true}),T('“Short on the dock”',36,'b','text/inverse'));
ad(sc,T('Why it matters',13,'b','accent/amber',{up:true,ls:6}),T('At 03:40 a loader finds 2 of 6 yoghurt crates missing for a Fresh stop, minutes before departure. Today the truck leaves anyway, the store finds out at 06:00, and the dispute depends on memory. Fresh departures can’t wait: every minute of delay pushes later stops towards the 08:00 opening.',16,'r','text/on-ink-muted',{w:548}));
ad(sc,T('Design response',13,'b','accent/amber',{up:true,ls:6}));for(const t of ['Loader flags it with a photo in 20 seconds (L3)','Dispatcher gets feasible options with their consequences, not just an alert','The chosen option updates the load list, driver run and store notice at once','Every outcome is recorded against the order for later disputes'])ad(sc,(()=>{const r=A('H',{gap:10});ad(r,I('check',18,'accent/amber'),T(t,15,'r','text/inverse',{w:500}));return r;})());
ad(sc,T('Related screens: L3 (loader flag) · D4 (exception) · S2/S4 (store)',13,'m','text/on-ink-muted'));
{const fr=screen(S,780,200,1440,900,'DG6','Dispatcher · resolve a dock shortfall','The shortfall arrives as a decision, not just an alert: three feasible options, each with its consequence for lateness and stores, and a recommended default that respects the Fresh departure deadline. One confirmation updates the load list on the dock tablet, the driver’s run and the store notice together, and the choice is logged.',{d:'H'});
ad(fr,[dsb('Plan & allocate'),'h']);const main=A('V',{n:'Main (dimmed)'});ad(fr,[main,'wh']);
ad(main,[dhead('Plan & allocate','Mon 02 Nov · published v3 · 03:41',[pill('Fresh wave departing','warning',{i:'clock'})],[btn('Publish to loaders','primary',{i:'upload'})]),'w']);
const bg=A('V',{p:28,gap:12});ad(main,[bg,'wh']);for(let i=0;i<5;i++){const r=card({h:120});ad(bg,[r,'w']);}
const ov=figma.createRectangle();ov.name='Scrim';ov.resize(1440,900);ov.fills=[P('bg/ink',0.55)];ad(fr,ov);ov.layoutPositioning='ABSOLUTE';ov.x=0;ov.y=0;
const m=A('V',{n:'Modal',bg:'bg/surface',r:16,w:720,p:0,gap:0,sh:2,clip:true});ad(fr,m);m.layoutPositioning='ABSOLUTE';m.x=360;m.y=70;
const mh=A('H',{p:[20,24],gap:12,ai:'CENTER',st:'border/default',sides:[0,0,1,0]});const ib=A('H',{bg:'tone/warning-soft',r:10,p:8});ad(ib,I('box',22,'tone/warning'));const mt=A('V',{gap:2});ad(mt,T('VEH022 held at Bay 2 · shortfall',19,'b'),T('Flagged by Kasun at 03:39 · departs 03:45 · 5 Fresh stops',13,'r','text/secondary'));ad(mh,ib,[mt,'g'],I('x',20,'text/muted'));ad(m,[mh,'w']);
const mb=A('V',{p:24,gap:14});ad(m,[mb,'w']);
const it=A('H',{bg:'bg/canvas',r:12,p:12,gap:12,ai:'CENTER'});const ph=A('V',{w:72,h:56,r:8,bg:'bg/ink-2',ai:'CENTER',jc:'CENTER'});ad(ph,I('camera',18,'text/on-ink-muted'));const itx=A('V',{gap:2});ad(itx,T('Yoghurt 80g crates for OUT027 Wellawatte',14,'s'),T('Loaded 4 of 6 · missing 2 · chilled',13,'r','text/secondary'));ad(it,ph,[itx,'g'],pill('Short 2','warning'));ad(mb,[it,'w']);
ad(mb,T('Choose how to resolve',14,'b'));
for(const [sel,title,rec,desc,imp] of [[1,'Release now with shortfall','Recommended','VEH022 leaves on time. OUT027 is told 4 of 6 crates arrive; the missing 2 go on tomorrow’s run with priority.',[['On time','success'],['Store notified','info']]],[0,'Re-pick missing crates','','Hold VEH022 for 12 min while stock is picked. All 5 stops shift later.',[['+12 min','warning'],['OUT041 late risk 61%','danger']]],[0,'Send missing crates on VEH057','','Reefer van has 1.2 m³ free on its Colombo trip, arriving at OUT027 06:35.',[['Feasible','success'],['+9 min for VEH057','warning']]]]){
const o=A('V',{p:16,r:12,gap:8,st:sel?'accent/primary':'border/default',sw:sel?2:1,bg:sel?'accent/primary-soft':'bg/surface'});const oh=A('H',{gap:10,ai:'CENTER'});const rd=A('H',{w:22,h:22,r:999,st:sel?'accent/primary':'border/strong',sw:2,ai:'CENTER',jc:'CENTER'});if(sel)ad(rd,dot(10,'accent/primary'));ad(oh,rd,T(title,15,'b'));if(rec)ad(oh,pill(rec,'primary',{solid:true}));ad(o,oh,[T(desc,13,'r','text/secondary',{w:600}),'w']);const ch=A('H',{gap:6});for(const [l,t] of imp)ad(ch,pill(l,t));ad(o,ch);ad(mb,[o,'w']);}
const mf=A('H',{p:[16,24],gap:10,st:'border/default',sides:[1,0,0,0],ai:'CENTER'});ad(mf,[T('Updates: dock tablet · driver run · store notice · deferral log',12,'r','text/muted'),'g'],btn('Cancel','secondary'),btn('Apply & notify','primary',{i:'check'}));ad(m,[mf,'w']);}
const n3=A('V',{n:'Scenario 3 note',bg:'bg/canvas',st:'border/default',r:16,p:24,gap:8,w:620});S.appendChild(n3);n3.x=80;n3.y=860;ad(n3,pill('ALSO COVERED','neutral',{lg:true}),T('“Demand beats the fleet”',20,'b'),T('The pre-festival peak, when chilled demand exceeds reefer capacity, is the core business problem, so it is designed into the normal flow: see D2 (binding constraint, deferral reasons and priority score), D3 (fairness history) and S3 (store deferral notice).',14,'r','text/secondary',{w:572}));
return {section:S.id};
